import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Nav/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Skibidi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex`}>
        {/* Sidebar Navbar */}
        <Navbar />
        {/* Main Content */}
        <div className="flex-grow md:ml-60 ml-0 p-4 md:p-6 bg-[#FDFCDC] min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
